#!/bin/bash

VH_ROOT=$(realpath $PWD)
while [ ! -d "$VH_ROOT/.stuff" ]; do
	VH_ROOT=$(realpath $VH_ROOT/..)
done
echo "Root directory is $VH_ROOT"

export VH_ROOT=$VH_ROOT
export VH_BIN=$VH_ROOT/.stuff/bin
export VH_LIB=$VH_ROOT/.stuff/lib
export PATH=$PATH:$VH_BIN

export VH_LAYER_ROOT=$VH_ROOT/layer
export VH_LAYER_DUMP=$VH_LAYER_ROOT/dump
export VH_LAYER_OVERRIDE=$VH_LAYER_ROOT/override

export VH_WORKSPACE=$VH_ROOT/workspace

if [ -f "$VH_WORKSPACE/config.sh" ]; then
	source $VH_WORKSPACE/config.sh
fi
