steps:
  # download-tag-file:
  #   image: curlimages/curl:8.8.0
  #   directory: vulkan_layer
  #   commands:
  #     - curl -L --create-dirs --output build/cppreference-doxygen-web.tag.xml https://upload.cppreference.com/mwiki/images/f/f8/cppreference-doxygen-web.tag.xml
  doxygen:
    image: greenbone/doxygen
    directory: vulkan_layer
    commands:
      - mkdir -p build
      - cd build
      - sed -e 's/@CMAKE_CURRENT_BINARY_DIR@/./' -e 's/@CMAKE_CURRENT_SOURCE_DIR@/../' ../docs/Doxyfile.in > Doxyfile
      - doxygen
  upload:
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      port:
        from_secret: ssh_port
      target: /config/data/docs/cheeky-imp/vulkan_layer
      source: vulkan_layer/build/docs/html/
      strip_components: 4
